### ISSUE TITLE
顺手来个码上看股多好

### ISSUE THREAD

**Issue by leeguooooo** [stack-stark/observe-chicken-in-code#1]

**Comment by stack-stark** [comment]
可以看看有个叫做 韭菜盒子 的vscode插件 我看股票也是用那个 @leeguooooo

**Comment by leeguooooo** [comment]
> 

亏麻了， 现在不想再看了 😭

**Comment by stack-stark** [comment]
![image](https://user-images.githubusercontent.com/46991054/156144518-1e0b6702-d2cb-46b0-9f33-76c83d577f64.png)
